pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            url = uri("https://maven.pkg.github.com/pitamen/blink-effect")
            credentials {
                username = "pitamen"
                password = "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"
            }
        }
    }
}

rootProject.name = "BlinkEffectExample"
include ':app'
include ':BlinkEffect'
